In [1]:
import numpy

a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
type(a)

numpy.ndarray

In [3]:
a.shape

(12,)

In [5]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a[2]

array([ 8,  9, 10, 11])

In [7]:
a[:,1]

array([1, 5, 9])

In [8]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [9]:
floats = numpy.loadtxt('floats.txt')
floats[-3:]

FileNotFoundError: floats.txt not found.

In [ ]:
from time import perf_counter as pc

t0 = pc()
floats /=3
time_cost = pc()-t0

numpy.save('floats-10M',floats)
floats2 = numpy.load('floats-10M.npy','r+')

